---
- name: Init | RedHat/CentOS | Adds Python pip
  yum:
    name: python-pip
    state: present
  when: ansible_os_family == 'RedHat'

- name: Init | Debian | Adds Python pip
  apt:
    pkg: python-pip
    state: present
  when: ansible_os_family == 'Debian'

- name: Init | Debian | Install libmariadbclient-dev
  apt:
    pkg: libmariadbclient-dev
    state: present
  when: ansible_os_family == 'Debian'
