---
- name: Init | RedHat/CentOS | Adds Python pip
  yum:
    name: python-setuptools
    state: present
  when: ansible_os_family == 'RedHat'

- name: Init | RedHat/CentOS | Adds Python pip
  easy_install:
    name: pip
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Init | RedHat/CentOS | Adds Python pip
  yum:
    name: python-pip
    state: present
  when: ansible_os_family == 'RedHat'

- name: Init | Debian | Adds Python pip
  apt:
    pkg: python-pip
    state: present
  when: ansible_os_family == 'Debian'

- name: Init | Debian | Install needed packages
  apt:
    pkg: ['libmariadbclient-dev', 'libffi-dev', 'libssl-dev']
    state: present
  when: ansible_os_family == 'Debian'
