---
- name: Docker |  RedHat/CentOS | Install required docker packages
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'nfs-utils']
    state: latest
  become: true
  when: ansible_os_family == 'RedHat'

- name: Docker | Debian | allow repository over HTTPS
  apt:
    pkg: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
    state: latest
  when: ansible_os_family == 'Debian'

- name: Docker | RedHat/CentOS | Get docker .repo file
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: ansible_os_family == 'RedHat'

- name: Docker | Debian | Import docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Docker | Debian | Update apt docker repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ default_docker_distribution_release }} stable'
    state: present
  when: ansible_os_family == 'Debian'

- name: Docker | RedHat/CentOS | Install Docker
  yum:
    name: docker-ce
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Docker | Debian | Install Docker
  apt:
    pkg: docker-ce
    state: latest
  when: ansible_os_family == 'Debian'

- name: Docker | Check if docker.service already exists
  stat:
    path: /etc/systemd/system/multi-user.target.wants/docker.service
  register: docker_service_exists

- name: Docker | Configure Docker daemon
  template:
    src: docker.service.conf.j2
    dest: /etc/systemd/system/multi-user.target.wants/docker.service
  notify:
    - reload systemd
    - restart docker daemon

- name: Docker | Enable & start Docker daemon
  service:
    name: docker
    enabled: yes
    state: restarted
    daemon_reload: yes
  when: docker_service_exists.stat.exists == False
