---

- name: SSL | Install PIP Python2
  yum:
    name: python-pip
    state: latest

- name: SSL | Install PIP pyOpenSSL module
  pip:
    name: pyOpenSSL
    state: latest

- name: SSL | Creates certificates directory
  file:
    path: "{{ default_mosquitto_certificates_path }}"
    state: directory
    owner: mosquitto
    group: mosquitto
    mode: 0700

- name: SSL | Generate an OpenSSL CA key.
  openssl_privatekey:
    path: "{{ default_mosquitto_certificates_path }}mosquitto_ca.key"
    size: 4096

- name: SSL | Generate an OpenSSL CRT for certificate.
  openssl_csr:
    path:  "{{ default_mosquitto_certificates_path }}mosquitto_ca.csr"
    privatekey_path: "{{ default_mosquitto_certificates_path }}mosquitto_ca.key"
    common_name: "{{ domain_name }}"

- name: SSL | Generate an OpenSSL certificate for the CA.
  openssl_certificate:
    path: "{{ default_mosquitto_certificates_path }}mosquitto_ca.crt"
    privatekey_path: "{{ default_mosquitto_certificates_path }}mosquitto_ca.key"
    csr_path: "{{ default_mosquitto_certificates_path }}mosquitto_ca.csr"
    provider: selfsigned

- name: SSL | Generate an OpenSSL server key.
  openssl_privatekey:
    path: "{{ default_mosquitto_certificates_path }}mosquitto_server.key"
    size: 4096

- name: SSL | Generate an OpenSSL CSR.
  openssl_csr:
    path:  "{{ default_mosquitto_certificates_path }}mosquitto_server.csr"
    privatekey_path: "{{ default_mosquitto_certificates_path }}mosquitto_server.key"
    common_name: "{{ domain_name }}"

- name: SSL | Generate certificate
  shell: openssl x509 -req -in {{ default_mosquitto_certificates_path }}mosquitto_server.csr -CA {{ default_mosquitto_certificates_path }}mosquitto_ca.crt -CAkey {{ default_mosquitto_certificates_path }}mosquitto_ca.key -CAcreateserial -out {{ default_mosquitto_certificates_path }}mosquitto_server.crt -days 360

#- name: SSL | Generate a Self Signed OpenSSL certificate.
#  openssl_certificate:
#    path: "{{ default_mosquitto_certificates_path }}mosquitto.{{ domain_name }}.crt"
#    privatekey_path: "{{ default_mosquitto_certificates_path }}mosquitto.{{ domain_name }}.key"
#    csr_path: "{{ default_mosquitto_certificates_path }}mosquitto.{{ domain_name }}.csr"
#    provider: selfsigned

- name: SSL | Open TLS Ports
  firewalld:
    zone: public
    port: "{{ item.port }}"
    permanent: "{{ item.permanent }}"
    state: enabled
  with_items:
    - { port: '{{ default_mosquitto_tls_port }}/tcp', permanent: true }

- name: SSL | Reload firewalld
  shell: firewall-cmd --reload

#- name: SSL | Set certificates directiry permissions
#  file:
#    path: "{{ default_mosquitto_certificates_path }}"
#    owner: root
#    group: root
#    state: directory
#    mode: 0700
#    recurse: yes