---
- name: Systemd | Set mosquitto.service
  template:
    src: mosquitto.service.j2
    dest: /etc/systemd/system/mosquitto.service
    owner: root
    group: root
    mode: 0644

- name: Systemd | Issue daemon-reload, restart Mosquitto and enable it
  systemd:
    state: restarted
    daemon_reload: yes
    name: mosquitto.service
    enabled: yes
