---

- name: BKS |  RedHat/CentOS | Install Java
  yum:
    name: ['java-1.8.0-openjdk-devel']
    state: latest
  when: ansible_os_family == 'RedHat'

- name: BKS | Debian | Install Java
  apt:
    pkg: ['openjdk-11-jre']
    install_recommends: yes
    state: latest
  when: ansible_os_family == 'Debian'

- name: BKS | Check if bouncycastle .jar already downloaded
  stat:
    path: /home/bcprov-jdk15on-158.jar
  register: bks_jar_found

- name: BKS | Download bouncycastle .jar
  get_url:
    url: https://www.bouncycastle.org/download/bcprov-jdk15on-158.jar
    dest: /home/bcprov-jdk15on-158.jar
    mode: 0744
    owner: root
    group: root
  when: bks_jar_found.stat.exists == False

- name: BKS | Delete BKS file if exists
  file:
    path: "{{ mosquitto_certificates_bks_path | default(default_mosquitto_certificates_bks_path) }}"
    state: absent

- name: BKS | Create BKS file
  shell: keytool -importcert -noprompt -v -trustcacerts -file '{{ mosquitto_certificates_crt_path | default(default_mosquitto_certificates_crt_path) }}' -alias IntermediateCA -keystore '{{ mosquitto_certificates_bks_path | default(default_mosquitto_certificates_bks_path) }}' -provider org.bouncycastle.jce.provider.BouncyCastleProvider -providerpath '/home/bcprov-jdk15on-158.jar' -storetype BKS -storepass "{{ mosquitto_bks_file_password | default(default_mosquitto_bks_file_password) }}"

- name: BKS | Copy created BKS file to guest machine
  fetch:
    src: "{{ mosquitto_certificates_bks_path | default(default_mosquitto_certificates_bks_path) }}"
    dest: /tmp

- name: BKS | Set facts
  set_fact:
    bks_pass: "{{ mosquitto_bks_file_password | default(default_mosquitto_bks_file_password) }}"

- name: BKS | Print BSK password
  debug:
    msg: "BKS password used is: {{ bks_pass }}"
