---

- name: MariaDB | Debian | Adds Python MySQL support on Debian/Ubuntu
  apt:
    pkg: python-mysqldb
    state: present
  when: ansible_os_family == 'Debian'

- name: MariaDB | RedHat/CentOS | Adds Python MySQL support
  yum:
    name: MySQL-python
    state: present
  when: ansible_os_family == 'RedHat'

#- name: MariaDB | Set nalkinscloud.sql.j2 file
#  template:
#    src: nalkinscloud.sql.j2
#    dest: /tmp/nalkinscloud.sql
#
#- name: DB Config | Create nalkinscloud database
#  mysql_db:
#    login_user: root
#    login_password: "{{ database_root_password | default(default_database_root_password) }}"
#    name: "{{ database_name | default(default_database_name) }}"
#    state: import
#    target: /tmp/nalkinscloud.sql

- name: DB Config | Create nalkinscloud database
  mysql_db:
    login_user: root
    login_password: "{{ database_root_password | default(default_database_root_password) }}"
    name: "{{ database_name | default(default_database_name) }}"
    state: present

- name: DB Config | Create 'mosquitto' user
  mysql_user:
    login_user: root
    login_password: "{{ database_root_password | default(default_database_root_password) }}"
    name: "{{ mosquitto_database_username | default(default_mosquitto_database_username) }}"
    password: "{{ mosquitto_database_password | default(default_mosquitto_database_password) }}"
    priv: '*.*:ALL'
    host: "{{ item }}"
    state: present
  with_items:
#    - "{{ mosquitto_database_host| default(default_mosquitto_database_host) }}"
    - "%"

- name: DB Config | Create 'mqtt2db' user
  mysql_user:
    login_user: root
    login_password: "{{ database_root_password | default(default_database_root_password) }}"
    name: "{{ mqtt2db_database_username | default(default_mqtt2db_database_username) }}"
    password: "{{ mqtt2db_database_password | default(default_mqtt2db_database_password) }}"
    priv: '*.*:ALL'
    host: "{{ item }}"
    state: present
  with_items:
#    - "{{ mqtt2db_database_host| default(default_mqtt2db_database_host) }}"
    - "%"

- name: DB Config | Create 'django' user
  mysql_user:
    login_user: root
    login_password: "{{ database_root_password | default(default_database_root_password) }}"
    name: "{{ django_database_username | default(default_django_database_username) }}"
    password: "{{ django_database_password | default(default_django_database_password) }}"
    priv: '*.*:ALL'
    host: "{{ item }}"
    state: present
  with_items:
#    - "{{ django_database_host| default(default_django_database_host) }}"
    - "%"
