---

- name: MariaDB | Debian | Adds Python MySQL support on Debian/Ubuntu
  apt:
    pkg: python-mysqldb
    state: present
  when: ansible_os_family == 'Debian'

- name: MariaDB | RedHat/CentOS | Adds Python MySQL support
  yum:
    name: MySQL-python
    state: present
  when: ansible_os_family == 'RedHat'

- name: DB Config | Create nalkinscloud database
  mysql_db:
    login_user: root
    login_password: "{{ database_root_password | default(default_database_root_password) }}"
    name: "{{ database_name | default(default_database_name) }}"
    state: present

- name: DB Config | Create 'mosquitto' user
  mysql_user:
    login_user: root
    login_password: "{{ database_root_password | default(default_database_root_password) }}"
    name: "{{ mosquitto_database_username | default(default_mosquitto_database_username) }}"
    password: "{{ mosquitto_database_password | default(default_mosquitto_database_password) }}"
    priv: '{{ mosquitto_database_name | default(default_mosquitto_database_name) }}.*:ALL'
    host: "{{ default_mosquitto_database_host }}"
    state: present

- name: DB Config | Create 'mqtt2db' user
  mysql_user:
    login_user: root
    login_password: "{{ database_root_password | default(default_database_root_password) }}"
    name: "{{ mqtt2db_database_username | default(default_mqtt2db_database_username) }}"
    password: "{{ mqtt2db_database_password | default(default_mqtt2db_database_password) }}"
    priv: '{{ mqtt2db_database_name | default(default_mqtt2db_database_name) }}.*:ALL'
    host: "{{ default_mqtt2db_database_host }}"
    state: present

- name: DB Config | Create 'django' user
  mysql_user:
    login_user: root
    login_password: "{{ database_root_password | default(default_database_root_password) }}"
    name: "{{ django_database_username | default(default_django_database_username) }}"
    password: "{{ django_database_password | default(default_django_database_password) }}"
    priv: '{{ django_database_name | default(default_django_database_name) }}.*:ALL'
    host: "{{ default_django_database_host }}"
    state: present